### ISSUE TITLE
There are two more project specific style settings and a map setting we need to interpret

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/vicav-vue3#30]
```json
    "map":{
      "zoom":7,
      "center":{
        "lat":35,
        "lng":9
      }
    },
    "styleSettings":{
      "colors":{
        "nav":"#7C633F",
        "subNav":"FFA500"
      }
    },
    "style":"<a css snippet> "
  }
```

see `curl -X GET "https://shawi.acdh-ch-dev.oeaw.ac.at/vicav/project" -H "accept: application/json"`

**Comment by MauPalantir** [comment]
"style" is a full custom css for a given project, that was the styling method for legacy vicav --- because we had a lot of custom styling requests for Tunocent and the code wasn't really built with styling in mind.

"styleSettings" is not used anywhere in the legacy vicav, I just introduced it for SHAWI to start a easier-to use styling method, but I would not care about it much until we talk about it with you frontend guys --- the structure and content should be whatever is easy to use by the frontend and what we want to allow customizing.

**Comment by stefanprobst** [comment]
initial map view state (center, zoom) as well as brand colors are now being read from `/project` config endpoint , so i think this issue can be closed.

**Comment by ctot-nondef** [comment]
@simar0at from my point of view this is resolved - please close as you see fit

**Comment by simar0at** [comment]
We want to change the style settings from #RGB to hsl(r,g,b,a)
```json
    "styleSettings":{
      "colors":{
        "nav":"#7C633F",
        "subNav":"FFA500",
        "primary: "hsla(35, 33%, 37%, 1)",
        "secondary": "hsla(39, 100%, 50%, 1)"
      }
  ```
  https://hslpicker.com/

**Comment by ctot-nondef** [comment]
[project endpoint](https://vicav.acdh-ch-dev.oeaw.ac.at/vicav/project) updated - adjust in frontend

**Comment by ctot-nondef** [comment]
styles injected [here](https://github.com/acdh-oeaw/vicav-vue3/blob/e47aab793429afa2c09d5a63d671808bec59c428/layouts/default.vue#L26) , currently parsing hsla values fails
